name: dispatcher
description: Simple messaging with end-to-end encryption
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: '^1.0.0'
  firebase_core: '^0.5.0+1'
  firebase_auth: '^0.18.0+2'
  firebase_analytics: '^6.0.1'
  firebase_storage: '^4.0.0'
  firebase_messaging: '^7.0.3'
  firebase_crashlytics: '^0.2.1+1'
  cloud_firestore: '^0.14.0+2'
  cloud_functions: '^0.6.0'
  async: '^2.4.1'
  intl: '^0.16.1'
  bloc: '^6.0.3'
  flutter_bloc: '^6.0.5'
  hydrated_bloc: '^6.0.1'
  graphql_flutter: '^3.1.0'
  provider: '^4.3.2+2'
  equatable: '^1.2.5'
  contacts_service: '^0.4.6'
  permission_handler: '^5.0.1+1'
  screen: '^0.0.5'
  share: '^0.6.4+3'
  uni_links: '^0.4.0'
  intl_phone_number_input: '^0.5.2+2'
  camera: '^0.5.8+5'
  image_picker: '^0.6.7+11'
  cached_network_image: '^2.2.0+1'
  circular_menu: '^1.1.0'
  logger: '^0.9.2'
  supercharged: '^1.10.0'
  formz: '^0.3.1'
  tuple: '^1.0.3'
  timezone: '^0.5.7'
  environment_config: '^2.2.4'
  flutter_local_notifications: '^2.0.0+1'
  libsignal_protocol_dart: '^0.2.0'
  openpgp: '^0.9.9'
  get_storage: '^1.3.2'
  fixnum: ^0.10.11
  rxdart: '^0.24.1'
  sqflite: '^1.3.2+1'

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: '^1.15.7'
  build_runner: '^1.10.0'

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/gilroy/Gilroy-ExtraBold.ttf
          weight: 900