name: dispatcher_auth_repository
description: Dispatcher package that manages the user domain
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  equatable: '^1.2.5'
  meta: '^1.2.3'