name: Flutter

on:
  push: 
    branches: 
      - master

  pull_request: 
    branches: 
      - master

jobs: 
  name: Build Android
  buildandroid: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v1
      - 
        uses: actions/setup-java@v1
        with: 
          java-version: 12.x
      - 
        uses: subosito/flutter-action@v1
        with: 
          channel: stable
          flutter-version: "1.22.0"
      - 
        env: 
          DISPATCHER_DEV_FIREBASE_SECRET: "${{ secrets.DISPATCHER_DEV_FIREBASE_SECRET }}"
        name: "Decode android google-services.json"
        run: "echo $DISPATCHER_DEV_FIREBASE_SECRET > android/app/src/dev/google-services.json"
      - 
        env: 
          DISPATCHER_DEV_LOCAL_SECRET: "${{ secrets.DISPATCHER_DEV_LOCAL_SECRET }}"
        name: "Decode android local.properties"
        run: "echo $DISPATCHER_DEV_LOCAL_SECRET > android/local.properties"
      - 
        env: 
          DISPATCHER_DEV_ENV_SECRET: "${{ secrets.DISPATCHER_DEV_ENV_SECRET }}"
          DISPATCHER_DEV_ENV_CONFIG_SECRET: "${{ secrets.DISPATCHER_DEV_ENV_CONFIG_SECRET }}"
        name: "Decode environment config"
        run: "echo $DISPATCHER_DEV_ENV_SECRET > .env"
        run: "echo $DISPATCHER_DEV_ENV_CONFIG_SECRET > lib/env_config.dart"
      - 
        name: "Flutter get"
        run: "flutter pub get"
      - 
        name: "Flutter build dev appbundle"
        run: "flutter build appbundle -t lib/main_dev.dart --flavor dev --verbose"

  buildios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - 
        uses: actions/checkout@v1
      - 
        uses: actions/setup-java@v1
        with: 
          java-version: 12.x
      - 
        uses: subosito/flutter-action@v1
        with: 
          channel: stable
          flutter-version: "1.22.0"
      - 
        env: 
          DISPATCHER_DEV_ENV_SECRET: "${{ secrets.DISPATCHER_DEV_ENV_SECRET }}"
          DISPATCHER_DEV_ENV_CONFIG_SECRET: "${{ secrets.DISPATCHER_DEV_ENV_CONFIG_SECRET }}"
        name: "Decode environment config"
        run: "echo $DISPATCHER_DEV_ENV_SECRET > .env"
        run: "echo $DISPATCHER_DEV_ENV_CONFIG_SECRET > lib/env_config.dart"
      - 
        name: "Flutter get"
        run: "flutter pub get"
      - 
        name: "Flutter build dev appbundle"
        run: "flutter build ios --no-codesign"