name: Flutter

on:
  push: 
    branches: 
      - master

  pull_request: 
    branches: 
      - master

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v1
      - 
        uses: actions/setup-java@v1
        with: 
          java-version: 12.x
      - 
        uses: subosito/flutter-action@v1
        with: 
          channel: stable
          flutter-version: "1.22.0"
      - 
        env: 
          DISPATCHER_DEV_FIREBASE_SECRET: "${{ secrets.DISPATCHER_DEV_FIREBASE_SECRET }}"
        name: "Decode android google-services.json"
        run: "echo $DISPATCHER_DEV_FIREBASE_SECRET > android/app/src/dev/google-services.json"
      - 
        env: 
          DISPATCHER_DEV_LOCAL_SECRET: "${{ secrets.DISPATCHER_DEV_LOCAL_SECRET }}"
        name: "Decode android local.properties"
        run: "echo $DISPATCHER_DEV_LOCAL_SECRET > android/local.properties"
      - 
        env: 
          DISPATCHER_DEV_ENV_CONFIG_SECRET: "${{ secrets.DISPATCHER_DEV_ENV_CONFIG_SECRET }}"
        name: "Decode environment_config.yaml"
        run: "echo $DISPATCHER_DEV_ENV_CONFIG_SECRET > environment_config.yaml"
      - 
        name: "Flutter get"
        run: "flutter pub get"
      - 
        name: "Flutter build env config"
        run: "'flutter pub run environment_config:generate'"
      - 
        name: "Flutter build dev appbundle"
        run: "flutter build appbundle -t lib/main_dev.dart --flavor dev --verbose"